"""Offline location choices for CRM address fields.

The country list is selectable independently. The bundled hierarchy currently
provides the complete India state/district data set; legacy state or district
values are preserved when existing CRM records are opened.
"""


COUNTRY_NAMES = tuple(sorted([
        "Afghanistan",
        "Åland Islands",
        "Albania",
        "Algeria",
        "American Samoa",
        "Andorra",
        "Angola",
        "Anguilla",
        "Antarctica",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Aruba",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bermuda",
        "Bhutan",
        "Bolivia, Plurinational State of",
        "Bonaire, Sint Eustatius and Saba",
        "Bosnia and Herzegovina",
        "Botswana",
        "Bouvet Island",
        "Brazil",
        "British Indian Ocean Territory",
        "Brunei Darussalam",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cabo Verde",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Cayman Islands",
        "Central African Republic",
        "Chad",
        "Chile",
        "China",
        "Christmas Island",
        "Cocos (Keeling) Islands",
        "Colombia",
        "Comoros",
        "Congo",
        "Congo, Democratic Republic of the",
        "Cook Islands",
        "Costa Rica",
        "Côte d'Ivoire",
        "Croatia",
        "Cuba",
        "Curaçao",
        "Cyprus",
        "Czechia",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Eswatini",
        "Ethiopia",
        "Falkland Islands (Malvinas)",
        "Faroe Islands",
        "Fiji",
        "Finland",
        "France",
        "French Guiana",
        "French Polynesia",
        "French Southern Territories",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Gibraltar",
        "Greece",
        "Greenland",
        "Grenada",
        "Guadeloupe",
        "Guam",
        "Guatemala",
        "Guernsey",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Heard Island and McDonald Islands",
        "Holy See",
        "Honduras",
        "Hong Kong",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran, Islamic Republic of",
        "Iraq",
        "Ireland",
        "Isle of Man",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Jersey",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Korea, Democratic People's Republic of",
        "Korea, Republic of",
        "Kuwait",
        "Kyrgyzstan",
        "Lao People's Democratic Republic",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macao",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Martinique",
        "Mauritania",
        "Mauritius",
        "Mayotte",
        "Mexico",
        "Micronesia, Federated States of",
        "Moldova, Republic of",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Montserrat",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands, Kingdom of the",
        "New Caledonia",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Niue",
        "Norfolk Island",
        "North Macedonia",
        "Northern Mariana Islands",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Palestine, State of",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Pitcairn",
        "Poland",
        "Portugal",
        "Puerto Rico",
        "Qatar",
        "Réunion",
        "Romania",
        "Russian Federation",
        "Rwanda",
        "Saint Barthélemy",
        "Saint Helena, Ascension and Tristan da Cunha",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Martin (French part)",
        "Saint Pierre and Miquelon",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Sint Maarten (Dutch part)",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "South Georgia and the South Sandwich Islands",
        "South Sudan",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Svalbard and Jan Mayen",
        "Sweden",
        "Switzerland",
        "Syrian Arab Republic",
        "Taiwan, Province of China",
        "Tajikistan",
        "Tanzania, United Republic of",
        "Thailand",
        "Timor-Leste",
        "Togo",
        "Tokelau",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Türkiye",
        "Turkmenistan",
        "Turks and Caicos Islands",
        "Tuvalu",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom of Great Britain and Northern Ireland",
        "United States of America",
        "United States Minor Outlying Islands",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Venezuela, Bolivarian Republic of",
        "Viet Nam",
        "Virgin Islands (British)",
        "Virgin Islands (U.S.)",
        "Wallis and Futuna",
        "Western Sahara",
        "Yemen",
        "Zambia",
        "Zimbabwe",
]))


# The hierarchy is a bundled snapshot of the public Indian-States-And-Districts
# data set (sanjaynishad/Indian-States-And-Districts). Keeping it in Python
# avoids a separate runtime data-file dependency in source and PyInstaller builds.
# State records use the state code as a stable reference; the UI stores the
# readable state name. Snapshot: Indian-States-And-Districts, 25 Sep 2026.
INDIA_STATE_RECORDS = [
    {
        "code":  "AN",
        "name":  "Andaman and Nicobar Islands",
        "districts":  [
                          "Nicobars",
                          "North And Middle Andaman",
                          "South Andamans"
                      ]
    },
    {
        "code":  "AP",
        "name":  "Andhra Pradesh",
        "districts":  [
                          "Alluri Sitharama Raju",
                          "Anakapalli",
                          "Ananthapuramu",
                          "Annamayya",
                          "Bapatla",
                          "Chittoor",
                          "Dr. B.R. Ambedkar Konaseema",
                          "East Godavari",
                          "Eluru",
                          "Guntur",
                          "Kakinada",
                          "Krishna",
                          "Kurnool",
                          "Markapuram",
                          "Nandyal",
                          "Ntr",
                          "Palnadu",
                          "Parvathipuram Manyam",
                          "Polavaram",
                          "Prakasam",
                          "Sri Potti Sriramulu Nellore",
                          "Sri Sathya Sai",
                          "Srikakulam",
                          "Tirupati",
                          "Visakhapatnam",
                          "Vizianagaram",
                          "West Godavari",
                          "Y.S.R. Kadapa"
                      ]
    },
    {
        "code":  "AR",
        "name":  "Arunachal Pradesh",
        "districts":  [
                          "Anjaw",
                          "Bichom",
                          "Changlang",
                          "Dibang Valley",
                          "East Kameng",
                          "East Siang",
                          "Kamle",
                          "Keyi Panyor",
                          "Kra Daadi",
                          "Kurung Kumey",
                          "Leparada",
                          "Lohit",
                          "Longding",
                          "Lower Dibang Valley",
                          "Lower Siang",
                          "Lower Subansiri",
                          "Namsai",
                          "Pakke Kessang",
                          "Papum Pare",
                          "Shi Yomi",
                          "Siang",
                          "Tawang",
                          "Tirap",
                          "Upper Siang",
                          "Upper Subansiri",
                          "West Kameng",
                          "West Siang"
                      ]
    },
    {
        "code":  "AS",
        "name":  "Assam",
        "districts":  [
                          "Bajali",
                          "Baksa",
                          "Barpeta",
                          "Biswanath",
                          "Bongaigaon",
                          "Cachar",
                          "Charaideo",
                          "Chirang",
                          "Darrang",
                          "Dhemaji",
                          "Dhubri",
                          "Dibrugarh",
                          "Dima Hasao",
                          "Goalpara",
                          "Golaghat",
                          "Hailakandi",
                          "Hojai",
                          "Jorhat",
                          "Kamrup",
                          "Kamrup Metro",
                          "Karbi Anglong",
                          "Kokrajhar",
                          "Lakhimpur",
                          "Majuli",
                          "Marigaon",
                          "Nagaon",
                          "Nalbari",
                          "Sivasagar",
                          "Sonitpur",
                          "South Salmara Mancachar",
                          "Sribhumi",
                          "Tamulpur",
                          "Tinsukia",
                          "Udalguri",
                          "West Karbi Anglong"
                      ]
    },
    {
        "code":  "BR",
        "name":  "Bihar",
        "districts":  [
                          "Araria",
                          "Arwal",
                          "Aurangabad",
                          "Banka",
                          "Begusarai",
                          "Bhagalpur",
                          "Bhojpur",
                          "Buxar",
                          "Darbhanga",
                          "Gaya",
                          "Gopalganj",
                          "Jamui",
                          "Jehanabad",
                          "Kaimur (Bhabua)",
                          "Katihar",
                          "Khagaria",
                          "Kishanganj",
                          "Lakhisarai",
                          "Madhepura",
                          "Madhubani",
                          "Munger",
                          "Muzaffarpur",
                          "Nalanda",
                          "Nawada",
                          "Pashchim Champaran",
                          "Patna",
                          "Purbi Champaran",
                          "Purnia",
                          "Rohtas",
                          "Saharsa",
                          "Samastipur",
                          "Saran",
                          "Sheikhpura",
                          "Sheohar",
                          "Sitamarhi",
                          "Siwan",
                          "Supaul",
                          "Vaishali"
                      ]
    },
    {
        "code":  "CH",
        "name":  "Chandigarh",
        "districts":  [
                          "Chandigarh"
                      ]
    },
    {
        "code":  "CG",
        "name":  "Chhattisgarh",
        "districts":  [
                          "Balod",
                          "Balodabazar-Bhatapara",
                          "Balrampur-Ramanujganj",
                          "Bastar",
                          "Bemetara",
                          "Bijapur",
                          "Bilaspur",
                          "Dakshin Bastar Dantewada",
                          "Dhamtari",
                          "Durg",
                          "Gariyaband",
                          "Gaurela-Pendra-Marwahi",
                          "Janjgir-Champa",
                          "Jashpur",
                          "Kabeerdham",
                          "Khairagarh-Chhuikhadan-Gandai",
                          "Kondagaon",
                          "Korba",
                          "Korea",
                          "Mahasamund",
                          "Manendragarh-Chirmiri-Bharatpur(M C B)",
                          "Mohla-Manpur-Ambagarh Chouki",
                          "Mungeli",
                          "Narayanpur",
                          "Raigarh",
                          "Raipur",
                          "Rajnandgaon",
                          "Sakti",
                          "Sarangarh-Bilaigarh",
                          "Sukma",
                          "Surajpur",
                          "Surguja",
                          "Uttar Bastar Kanker"
                      ]
    },
    {
        "code":  "ND",
        "name":  "Dadra and Nagar Haveli and Daman and Diu",
        "districts":  [
                          "Dadra And Nagar Haveli",
                          "Daman",
                          "Diu"
                      ]
    },
    {
        "code":  "DL",
        "name":  "Delhi",
        "districts":  [
                          "Central",
                          "Central North",
                          "East",
                          "New Delhi",
                          "North",
                          "North East",
                          "North West",
                          "Old Delhi",
                          "Outer North",
                          "South",
                          "South East",
                          "South West",
                          "West"
                      ]
    },
    {
        "code":  "GA",
        "name":  "Goa",
        "districts":  [
                          "Kushavati",
                          "North Goa",
                          "South Goa"
                      ]
    },
    {
        "code":  "GJ",
        "name":  "Gujarat",
        "districts":  [
                          "Ahmedabad",
                          "Amreli",
                          "Anand",
                          "Arvalli",
                          "Banas Kantha",
                          "Bharuch",
                          "Bhavnagar",
                          "Botad",
                          "Chhotaudepur",
                          "Dahod",
                          "Dangs",
                          "Devbhumi Dwarka",
                          "Gandhinagar",
                          "Gir Somnath",
                          "Jamnagar",
                          "Junagadh",
                          "Kachchh",
                          "Kheda",
                          "Mahesana",
                          "Mahisagar",
                          "Morbi",
                          "Narmada",
                          "Navsari",
                          "Panch Mahals",
                          "Patan",
                          "Porbandar",
                          "Rajkot",
                          "Sabar Kantha",
                          "Surat",
                          "Surendranagar",
                          "Tapi",
                          "Vadodara",
                          "Valsad",
                          "Vav-Tharad"
                      ]
    },
    {
        "code":  "HR",
        "name":  "Haryana",
        "districts":  [
                          "Ambala",
                          "Bhiwani",
                          "Charkhi Dadri",
                          "Faridabad",
                          "Fatehabad",
                          "Gurugram",
                          "Hansi",
                          "Hisar",
                          "Jhajjar",
                          "Jind",
                          "Kaithal",
                          "Karnal",
                          "Kurukshetra",
                          "Mahendragarh",
                          "Nuh",
                          "Palwal",
                          "Panchkula",
                          "Panipat",
                          "Rewari",
                          "Rohtak",
                          "Sirsa",
                          "Sonipat",
                          "Yamunanagar"
                      ]
    },
    {
        "code":  "HP",
        "name":  "Himachal Pradesh",
        "districts":  [
                          "Bilaspur",
                          "Chamba",
                          "Hamirpur",
                          "Kangra",
                          "Kinnaur",
                          "Kullu",
                          "Lahaul And Spiti",
                          "Mandi",
                          "Shimla",
                          "Sirmaur",
                          "Solan",
                          "Una"
                      ]
    },
    {
        "code":  "JK",
        "name":  "Jammu and Kashmir",
        "districts":  [
                          "Anantnag",
                          "Bandipora",
                          "Baramulla",
                          "Budgam",
                          "Doda",
                          "Ganderbal",
                          "Jammu",
                          "Kathua",
                          "Kishtwar",
                          "Kulgam",
                          "Kupwara",
                          "Poonch",
                          "Pulwama",
                          "Rajouri",
                          "Ramban",
                          "Reasi",
                          "Samba",
                          "Shopian",
                          "Srinagar",
                          "Udhampur"
                      ]
    },
    {
        "code":  "JH",
        "name":  "Jharkhand",
        "districts":  [
                          "Bokaro",
                          "Chatra",
                          "Deoghar",
                          "Dhanbad",
                          "Dumka",
                          "East Singhbum",
                          "Garhwa",
                          "Giridih",
                          "Godda",
                          "Gumla",
                          "Hazaribagh",
                          "Jamtara",
                          "Khunti",
                          "Koderma",
                          "Latehar",
                          "Lohardaga",
                          "Pakur",
                          "Palamu",
                          "Ramgarh",
                          "Ranchi",
                          "Sahebganj",
                          "Saraikela Kharsawan",
                          "Simdega",
                          "West Singhbhum"
                      ]
    },
    {
        "code":  "KA",
        "name":  "Karnataka",
        "districts":  [
                          "Bagalkote",
                          "Ballari",
                          "Belagavi",
                          "Bengaluru Rural",
                          "Bengaluru South",
                          "Bengaluru Urban",
                          "Bidar",
                          "Chamarajanagar",
                          "Chikkaballapura",
                          "Chikkamagaluru",
                          "Chitradurga",
                          "Dakshina Kannada",
                          "Davanagere",
                          "Dharwad",
                          "Gadag",
                          "Hassan",
                          "Haveri",
                          "Kalaburagi",
                          "Kodagu",
                          "Kolar",
                          "Koppal",
                          "Mandya",
                          "Mysuru",
                          "Raichur",
                          "Shivamogga",
                          "Tumakuru",
                          "Udupi",
                          "Uttara Kannada",
                          "Vijayanagara",
                          "Vijayapura",
                          "Yadgir"
                      ]
    },
    {
        "code":  "KL",
        "name":  "Kerala",
        "districts":  [
                          "Alappuzha",
                          "Ernakulam",
                          "Idukki",
                          "Kannur",
                          "Kasaragod",
                          "Kollam",
                          "Kottayam",
                          "Kozhikode",
                          "Malappuram",
                          "Palakkad",
                          "Pathanamthitta",
                          "Thiruvananthapuram",
                          "Thrissur",
                          "Wayanad"
                      ]
    },
    {
        "code":  "LA",
        "name":  "Ladakh",
        "districts":  [
                          "Kargil",
                          "Leh Ladakh"
                      ]
    },
    {
        "code":  "LD",
        "name":  "Lakshadweep",
        "districts":  [
                          "Lakshadweep District"
                      ]
    },
    {
        "code":  "MP",
        "name":  "Madhya Pradesh",
        "districts":  [
                          "Agar-Malwa",
                          "Alirajpur",
                          "Anuppur",
                          "Ashoknagar",
                          "Balaghat",
                          "Barwani",
                          "Betul",
                          "Bhind",
                          "Bhopal",
                          "Burhanpur",
                          "Chhatarpur",
                          "Chhindwara",
                          "Damoh",
                          "Datia",
                          "Dewas",
                          "Dhar",
                          "Dindori",
                          "Guna",
                          "Gwalior",
                          "Harda",
                          "Indore",
                          "Jabalpur",
                          "Jhabua",
                          "Katni",
                          "Khandwa (East Nimar)",
                          "Khargone (West Nimar)",
                          "MAUGANJ",
                          "Maihar",
                          "Mandla",
                          "Mandsaur",
                          "Morena",
                          "Narmadapuram",
                          "Narsimhapur",
                          "Neemuch",
                          "Niwari",
                          "Pandhurna",
                          "Panna",
                          "Raisen",
                          "Rajgarh",
                          "Ratlam",
                          "Rewa",
                          "Sagar",
                          "Satna",
                          "Sehore",
                          "Seoni",
                          "Shahdol",
                          "Shajapur",
                          "Sheopur",
                          "Shivpuri",
                          "Sidhi",
                          "Singrauli",
                          "Tikamgarh",
                          "Ujjain",
                          "Umaria",
                          "Vidisha"
                      ]
    },
    {
        "code":  "MH",
        "name":  "Maharashtra",
        "districts":  [
                          "Ahilyanagar",
                          "Akola",
                          "Amravati",
                          "Beed",
                          "Bhandara",
                          "Buldhana",
                          "Chandrapur",
                          "Chhatrapati Sambhajinagar",
                          "Dharashiv",
                          "Dhule",
                          "Gadchiroli",
                          "Gondia",
                          "Hingoli",
                          "Jalgaon",
                          "Jalna",
                          "Kolhapur",
                          "Latur",
                          "Mumbai",
                          "Mumbai Suburban",
                          "Nagpur",
                          "Nanded",
                          "Nandurbar",
                          "Nashik",
                          "Palghar",
                          "Parbhani",
                          "Pune",
                          "Raigad",
                          "Ratnagiri",
                          "Sangli",
                          "Satara",
                          "Sindhudurg",
                          "Solapur",
                          "Thane",
                          "Wardha",
                          "Washim",
                          "Yavatmal"
                      ]
    },
    {
        "code":  "MN",
        "name":  "Manipur",
        "districts":  [
                          "Bishnupur",
                          "Chandel",
                          "Churachandpur",
                          "Imphal East",
                          "Imphal West",
                          "Jiribam",
                          "Kakching",
                          "Kamjong",
                          "Kangpokpi",
                          "Noney",
                          "Pherzawl",
                          "Senapati",
                          "Tamenglong",
                          "Tengnoupal",
                          "Thoubal",
                          "Ukhrul"
                      ]
    },
    {
        "code":  "ML",
        "name":  "Meghalaya",
        "districts":  [
                          "East Garo Hills",
                          "East Jaintia Hills",
                          "East Khasi Hills",
                          "Eastern West Khasi Hills",
                          "North Garo Hills",
                          "Ri Bhoi",
                          "South Garo Hills",
                          "South West Garo Hills",
                          "South West Khasi Hills",
                          "West Garo Hills",
                          "West Jaintia Hills",
                          "West Khasi Hills"
                      ]
    },
    {
        "code":  "MZ",
        "name":  "Mizoram",
        "districts":  [
                          "Aizawl",
                          "Champhai",
                          "Hnahthial",
                          "Khawzawl",
                          "Kolasib",
                          "Lawngtlai",
                          "Lunglei",
                          "Mamit",
                          "Saitual",
                          "Serchhip",
                          "Siaha"
                      ]
    },
    {
        "code":  "NL",
        "name":  "Nagaland",
        "districts":  [
                          "Chumoukedima",
                          "Dimapur",
                          "Kiphire",
                          "Kohima",
                          "Longleng",
                          "Meluri",
                          "Mokokchung",
                          "Mon",
                          "Niuland",
                          "Noklak",
                          "Peren",
                          "Phek",
                          "Shamator",
                          "Tseminyu",
                          "Tuensang",
                          "Wokha",
                          "Zunheboto"
                      ]
    },
    {
        "code":  "OD",
        "name":  "Odisha",
        "districts":  [
                          "Angul",
                          "Balangir",
                          "Balasore",
                          "Bargarh",
                          "Bhadrak",
                          "Boudh",
                          "Cuttack",
                          "Deogarh",
                          "Dhenkanal",
                          "Gajapati",
                          "Ganjam",
                          "Jagatsinghapur",
                          "Jajpur",
                          "Jharsuguda",
                          "Kalahandi",
                          "Kandhamal",
                          "Kendrapara",
                          "Keonjhar",
                          "Khordha",
                          "Koraput",
                          "Malkangiri",
                          "Mayurbhanj",
                          "Nabarangpur",
                          "Nayagarh",
                          "Nuapada",
                          "Puri",
                          "Rayagada",
                          "Sambalpur",
                          "Sonepur",
                          "Sundargarh"
                      ]
    },
    {
        "code":  "PY",
        "name":  "Puducherry",
        "districts":  [
                          "Karaikal",
                          "Puducherry"
                      ]
    },
    {
        "code":  "PB",
        "name":  "Punjab",
        "districts":  [
                          "Amritsar",
                          "Barnala",
                          "Bathinda",
                          "Faridkot",
                          "Fatehgarh Sahib",
                          "Fazilka",
                          "Ferozepur",
                          "Gurdaspur",
                          "Hoshiarpur",
                          "Jalandhar",
                          "Kapurthala",
                          "Ludhiana",
                          "Malerkotla",
                          "Mansa",
                          "Moga",
                          "Pathankot",
                          "Patiala",
                          "Rupnagar",
                          "S.A.S Nagar",
                          "Sangrur",
                          "Shahid Bhagat Singh Nagar",
                          "Sri Muktsar Sahib",
                          "Tarn Taran"
                      ]
    },
    {
        "code":  "RJ",
        "name":  "Rajasthan",
        "districts":  [
                          "Ajmer",
                          "Alwar",
                          "Balotra",
                          "Banswara",
                          "Baran",
                          "Barmer",
                          "Beawar",
                          "Bharatpur",
                          "Bhilwara",
                          "Bikaner",
                          "Bundi",
                          "Chittorgarh",
                          "Churu",
                          "Dausa",
                          "Deeg",
                          "Dholpur",
                          "Didwana-Kuchaman",
                          "Dungarpur",
                          "Ganganagar",
                          "Hanumangarh",
                          "Jaipur",
                          "Jaisalmer",
                          "Jalore",
                          "Jhalawar",
                          "Jhunjhunu",
                          "Jodhpur",
                          "Karauli",
                          "Khairthal-Tijara",
                          "Kota",
                          "Kotputli-Behror",
                          "Nagaur",
                          "Pali",
                          "Phalodi",
                          "Pratapgarh",
                          "Rajsamand",
                          "Salumbar",
                          "Sawai Madhopur",
                          "Sikar",
                          "Sirohi",
                          "Tonk",
                          "Udaipur"
                      ]
    },
    {
        "code":  "SK",
        "name":  "Sikkim",
        "districts":  [
                          "Gangtok",
                          "Gyalshing",
                          "Mangan",
                          "Namchi",
                          "Pakyong",
                          "Soreng"
                      ]
    },
    {
        "code":  "TN",
        "name":  "Tamil Nadu",
        "districts":  [
                          "Ariyalur",
                          "Chengalpattu",
                          "Chennai",
                          "Coimbatore",
                          "Cuddalore",
                          "Dharmapuri",
                          "Dindigul",
                          "Erode",
                          "Kallakurichi",
                          "Kancheepuram",
                          "Kanniyakumari",
                          "Karur",
                          "Krishnagiri",
                          "Madurai",
                          "Mayiladuthurai",
                          "Nagapattinam",
                          "Namakkal",
                          "Perambalur",
                          "Pudukkottai",
                          "Ramanathapuram",
                          "Ranipet",
                          "Salem",
                          "Sivaganga",
                          "Tenkasi",
                          "Thanjavur",
                          "The Nilgiris",
                          "Theni",
                          "Thiruvallur",
                          "Thiruvarur",
                          "Thoothukkudi",
                          "Tiruchirappalli",
                          "Tirunelveli",
                          "Tirupathur",
                          "Tiruppur",
                          "Tiruvannamalai",
                          "Vellore",
                          "Viluppuram",
                          "Virudhunagar"
                      ]
    },
    {
        "code":  "TS",
        "name":  "Telangana",
        "districts":  [
                          "Adilabad",
                          "Bhadradri Kothagudem",
                          "Hanumakonda",
                          "Hyderabad",
                          "Jagitial",
                          "Jangoan",
                          "Jayashankar Bhupalapally",
                          "Jogulamba Gadwal",
                          "Kamareddy",
                          "Karimnagar",
                          "Khammam",
                          "Kumuram Bheem Asifabad",
                          "Mahabubabad",
                          "Mahabubnagar",
                          "Mancherial",
                          "Medak",
                          "Medchal Malkajgiri",
                          "Mulugu",
                          "Nagarkurnool",
                          "Nalgonda",
                          "Narayanpet",
                          "Nirmal",
                          "Nizamabad",
                          "Peddapalli",
                          "Rajanna Sircilla",
                          "Ranga Reddy",
                          "Sangareddy",
                          "Siddipet",
                          "Suryapet",
                          "Vikarabad",
                          "Wanaparthy",
                          "Warangal",
                          "Yadadri Bhuvanagiri"
                      ]
    },
    {
        "code":  "TR",
        "name":  "Tripura",
        "districts":  [
                          "Dhalai",
                          "Gomati",
                          "Khowai",
                          "North Tripura",
                          "Sepahijala",
                          "South Tripura",
                          "Unakoti",
                          "West Tripura"
                      ]
    },
    {
        "code":  "UP",
        "name":  "Uttar Pradesh",
        "districts":  [
                          "Agra",
                          "Aligarh",
                          "Ambedkar Nagar",
                          "Amethi",
                          "Amroha",
                          "Auraiya",
                          "Ayodhya",
                          "Azamgarh",
                          "Baghpat",
                          "Bahraich",
                          "Ballia",
                          "Balrampur",
                          "Banda",
                          "Bara Banki",
                          "Bareilly",
                          "Basti",
                          "Bhadohi",
                          "Bijnor",
                          "Budaun",
                          "Bulandshahr",
                          "Chandauli",
                          "Chitrakoot",
                          "Deoria",
                          "Etah",
                          "Etawah",
                          "Farrukhabad",
                          "Fatehpur",
                          "Firozabad",
                          "Gautam Buddha Nagar",
                          "Ghaziabad",
                          "Ghazipur",
                          "Gonda",
                          "Gorakhpur",
                          "Hamirpur",
                          "Hapur",
                          "Hardoi",
                          "Hathras",
                          "Jalaun",
                          "Jaunpur",
                          "Jhansi",
                          "Kannauj",
                          "Kanpur Dehat",
                          "Kanpur Nagar",
                          "Kasganj",
                          "Kaushambi",
                          "Kheri",
                          "Kushinagar",
                          "Lalitpur",
                          "Lucknow",
                          "Mahoba",
                          "Mahrajganj",
                          "Mainpuri",
                          "Mathura",
                          "Mau",
                          "Meerut",
                          "Mirzapur",
                          "Moradabad",
                          "Muzaffarnagar",
                          "Pilibhit",
                          "Pratapgarh",
                          "Prayagraj",
                          "Rae Bareli",
                          "Rampur",
                          "Saharanpur",
                          "Sambhal",
                          "Sant Kabir Nagar",
                          "Shahjahanpur",
                          "Shamli",
                          "Shrawasti",
                          "Siddharthnagar",
                          "Sitapur",
                          "Sonbhadra",
                          "Sultanpur",
                          "Unnao",
                          "Varanasi"
                      ]
    },
    {
        "code":  "UK",
        "name":  "Uttarakhand",
        "districts":  [
                          "Almora",
                          "Bageshwar",
                          "Chamoli",
                          "Champawat",
                          "Dehradun",
                          "Haridwar",
                          "Nainital",
                          "Pauri Garhwal",
                          "Pithoragarh",
                          "Rudraprayag",
                          "Tehri Garhwal",
                          "Udham Singh Nagar",
                          "Uttarkashi"
                      ]
    },
    {
        "code":  "WB",
        "name":  "West Bengal",
        "districts":  [
                          "Alipurduar",
                          "Bankura",
                          "Birbhum",
                          "Cooch Behar",
                          "Dakshin Dinajpur",
                          "Darjeeling",
                          "Hooghly",
                          "Howrah",
                          "Jalpaiguri",
                          "Jhargram",
                          "Kalimpong",
                          "Kolkata",
                          "Malda",
                          "Murshidabad",
                          "Nadia",
                          "North 24 Parganas",
                          "Paschim Bardhaman",
                          "Paschim Medinipur",
                          "Purba Bardhaman",
                          "Purba Medinipur",
                          "Purulia",
                          "South 24 Parganas",
                          "Uttar Dinajpur"
                      ]
    }
]

INDIA_LOCATIONS = {
    record["name"]: tuple(record["districts"])
    for record in INDIA_STATE_RECORDS
}

LOCATION_HIERARCHY = {"India": INDIA_LOCATIONS}


def states_for_country(country):
    """Return selectable states/union territories for a country."""
    return tuple(LOCATION_HIERARCHY.get((country or "").strip(), {}).keys())


def districts_for_country(country, state):
    """Return selectable districts for the selected country and state."""
    state_districts = LOCATION_HIERARCHY.get((country or "").strip(), {})
    return tuple(state_districts.get((state or "").strip(), ()))


def canonical_name(value, choices):
    """Match a saved value to a current selectable option, ignoring case."""
    normalized = (value or "").strip().casefold()
    return next(
        (choice for choice in choices if choice.casefold() == normalized),
        "",
    )


def is_known_country(country):
    """Return whether a country is in the bundled country list."""
    return (country or "").strip() in COUNTRY_NAMES
